server.port=8083
spring.application.name=ai-service

management.endpoints.web.exposure.include=*

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.temperature=0.2